services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9002:9001"
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  bot:
    build: .
    container_name: bot
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    volumes:
      - ./db:/usr/src/app/db
    depends_on:
      - minio
